apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app-deploy
  labels:
    app: java-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
      - name: java-app
        image: gcr.io/solid-justice-272605/java-app:01
        ports:
        - containerPort: 8080
